bookmark() {

echo ""
	cecho "--------------------------------------------------------" $boldyellow
	cecho "Please bookmark:" $boldyellow
	cecho "--------------------------------------------------------" $boldyellow
cat <<EOF
###############################################################
* Getting Started Guide - http://centminmod.com/getstarted.html
* Find the latest Centmin Mod version - http://centminmod.com
* Centmin Mod FAQ - http://centminmod.com/faq.html
* Change Log - http://centminmod.com/changelog.html 
* Google+ Page latest news http://centminmod.com/gpage
* Community Forums https://community.centminmod.com (signup)
###############################################################
# Cheap VPS Hosting at Digitalocean 
# https://www.digitalocean.com/?refcode=c1cb367108e8
###############################################################
EOF

}