name: Trigger AlmaLinux 9 With PHP 8.2 Workflow

on:
  workflow_dispatch:
    branches: [130.00beta01]
  push:
    branches:
      - 130.00beta01
    paths-ignore:
      - '.gitignore'
      - 'readme.txt'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.github/workflows/main.yml'
      - '.github/workflows/cmm-centos7.yml'
      - '.github/workflows/cmm-almalinux8-vs-rockylinux8-vs-oraclelinux8.yml'
      - '.github/workflows/cmm-almalinux9-vs-rockylinux9-vs-oraclelinux9.yml'
      - '.github/workflows/cmm-oraclelinux9.yml'
      - '.github/workflows/cmm-oraclelinux8-edge.yml'
      - '.github/workflows/cmm-almalinux9.yml'
      - '.github/workflows/cmm-almalinux8-lua.yml'
      - '.github/workflows/cmm-almalinux9-lua.yml'
      - '.github/workflows/cmm-rockylinux9-lua.yml'
      - '.github/workflows/cmm-rockylinux8-lua.yml'
      - '.github/workflows/cmm-oraclelinux8-lua.yml'
      - '.github/workflows/cmm-oraclelinux9-lua.yml'
      - '.github/workflows/cmm-centos8stream-lua.yml'
      - '.github/workflows/cmm-centos9stream-lua.yml'
      - '.github/workflows/cmm-almalinux8-modsecurity.yml'
      - '.github/workflows/cmm-almalinux9-modsecurity.yml'
      - '.github/workflows/cmm-rockylinux9-modsecurity.yml'
      - '.github/workflows/cmm-rockylinux8-modsecurity.yml'
      - '.github/workflows/cmm-oraclelinux8-modsecurity.yml'
      - '.github/workflows/cmm-oraclelinux9-modsecurity.yml'
      - '.github/workflows/cmm-centos8stream-modsecurity.yml'
      - '.github/workflows/cmm-centos9stream-modsecurity.yml'
      - '.github/workflows/cmm-rockylinux9.yml'
      - '.github/workflows/cmm-rockylinux8.yml'
      - '.github/workflows/cmm-oraclelinux8.yml'
      - '.github/workflows/cmm-centos8stream.yml'
      - '.github/workflows/cmm-centos9stream.yml'
      - '.github/workflows/cmm-rockylinux8-edge.yml'
      - '.github/workflows/cmm-almalinux8-edge.yml'
      - '.github/workflows/cmm-rockylinux8-php7.4.yml'
      - '.github/workflows/cmm-almalinux8-php7.4.yml'
      - '.github/workflows/cmm-rockylinux8-php8.1.yml'
      - '.github/workflows/cmm-almalinux8-php8.1.yml'
      - '.github/workflows/cmm-rockylinux8-php8.2.yml'
      - '.github/workflows/cmm-almalinux8-php8.2.yml'
      - '.github/workflows/cmm-rockylinux9-php8.2.yml'
      - '.github/workflows/cmm-almalinux9-php8.2.yml'
      - '.github/workflows/cmm-almalinux9-mariadb10.6.yml'
      - '.github/workflows/cmm-rockylinux9-mariadb10.6.yml'
      - '.github/workflows/cmm-almalinux8-mariadb10.6.yml'
      - '.github/workflows/cmm-rockylinux8-mariadb10.6.yml'
      - '.github/workflows/cmm-almalinux9-mariadb10.11.yml'
      - '.github/workflows/cmm-rockylinux9-mariadb10.11.yml'
      - '.github/workflows/cmm-almalinux8-mariadb10.11.yml'
      - '.github/workflows/cmm-rockylinux8-mariadb10.11.yml'
      - '.github/workflows/cmm-almalinux8-mariadb10.4.yml'
      - '.github/workflows/cmm-rockylinux8-mariadb10.4.yml'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trigger centminmod-workflows workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: centminmod/centminmod-workflows
          event-type: run-almalinux-9-workflow-php82
